name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - run: dotnet build <my project>
